### ISSUE TITLE
Complex objects in session storage

### ISSUE THREAD

**Issue by HarelM** [zoomsphere/ngx-store#11]
I'm using the following interface to store a state of a dialog in the session storage:
```
interface IOsmUserDialogState {
    selectedTabIndex: number;
    searchTerm: string;
    scrollPosition: number;
    sharesPage: number;
    tracesPage: number;
}
```
I don't change the instance but only the internal fields.
Are those field being watched for changes?

**Comment by DanielKucal** [comment]
No, it's not possible for now. It will probably can be handled by ES6 Proxy feature - unfortunately it cannot be transpilled to ES5, so we have to wait for browsers implementations. That's why we have the `.save()` method added to decorated object. Alternatively you can assign the object to itself like `this.state = this.state;` to force save of internal object changes.

**Comment by HarelM** [comment]
I see, thanks for the quick response! currently I'm doing it using the `LocalSessionService` `get` `set` methods which is almost the same, I hoped to remove a few lines of code. Well, you win some you lose some :-)
Feel free to close this issue.

**Comment by DanielKucal** [comment]
Yup, using a service is another alternative solution - whatever you prefer ;)
