### ISSUE TITLE
Error compiling in latest angular-cli

### ISSUE THREAD

**Issue by jmls** [zoomsphere/ngx-store#2]
If I try and include ngx-store in my project, I get the following error when building

`ERROR in [snip]../node_modules/ts-debug/debug.d.ts (3,21): Namespace 'NodeJS' has no exported member 'ConsoleConstructor'.`

**Comment by DanielKucal** [comment]
Hi @jmls, thanks for your report. The error could occur when your project didn't have `@types/node` installed. I've made it a core dependency in `ts-debug` library. Reinstalling `ngx-store` should fix the problem. If not let me know and try with `npm install ts-debug --no-save` (for npm@5, for older version `--no-save` flag is redundant).

**Comment by codinronan** [comment]
@DanielKucal I got this too, all I had to do was explicitly install `@types/node` in my `devDependencies`. 

This worked for me; your mileage may vary.

**Comment by DanielKucal** [comment]
Hi @codinronan, which `ngx-store` version have you tried? I'm sure `@types/node` are installed as required dependency since version 1.0.3

**Comment by codinronan** [comment]
@DanielKucal hey :) Just installed yesterday, 1.0.3. I noticed that I already had `@types/node` installed though, but I had `^6.0.something` installed. When I did `yarn add @types/node` it updated to 8.0.0 and the error went away so that was it.

Lovely package, though. Makes my life easier, I hate working with local/session storage and cookies directly.

**Comment by DanielKucal** [comment]
Okay, thank you for checking this. I think we can close this issue now.
Also thanks for your appreciation! I hope a lot of people will find this project useful, so it'll be developed much further :)
