### ISSUE TITLE
Array functions remove class methods

### ISSUE THREAD

**Issue by manuelmeister** [zoomsphere/ngx-store#4]
If I add the localstorage decorator to an array of ``MyClass`` objects. I can't access the class methods anymore. They somehow get stripped in CacheItem when mutateObjects is set to true.

**Comment by DanielKucal** [comment]
Hi @manuelmeister, I think it's because functions cannot be `JSON.stringify`ied and saved.
![image](https://user-images.githubusercontent.com/8938562/27593724-3399c8aa-5b58-11e7-93b2-95f7d714d9fd.png)
It can work with turned off object mutations but just until you reload the page.
See for example these topics on stackoverflow: https://stackoverflow.com/questions/11063630/save-a-function-in-localstorage
https://stackoverflow.com/questions/7955965/how-come-json-cant-save-objects-functions
I guess you should implement `toJSON` and `fromJSON` methods in your class, where the first one will return only object fields (+ other data you want to save) and the second one will create class instance using provided data... Probably `fromJSON()` will be enough, but I haven't tried this yet.

**Comment by manuelmeister** [comment]
Okay, thanks.
