### ISSUE TITLE
@LocalStorage gets reassigned every time

### ISSUE THREAD

**Issue by bert-w** [zoomsphere/ngx-store#6]
```
@LocalStorage('sell-your-item') item: any =  {
        location: {},
        price: {
            currency: 'EUR'
        }
    };
```

When I set the currency for instance, and I reload the component, the object is reset to the properties above. This does not seem intended behaviour. I've tried working around this issue, but I'm also getting issues where the properties are not getting saved unless i call `save()` twice.

Next, ive tried to simulate the object behaviour, by having it manually saved as a JSON.stringified string. This also forced me to call .save() twice in order to save the changes.

**Comment by DanielKucal** [comment]
Hi @bert-w, I was trying to reproduce your issue, so I used your exact data and set `this.item.price.currency = 'USD';` then `this.item.save();`, reloaded the page and the value for price currency is 'USD' like it should to be. Is this variable shared across classes?

**Comment by bert-w** [comment]
yes the property was part of a component which was the parent of the one that would save it.

I went with the raw javascript solution `localStorage.setItem()` because i couldnt quite figure this bug out. The raw implementation works good though

**Comment by DanielKucal** [comment]
So the decorated property was passed as an `@Input()`?

**Comment by DanielKucal** [comment]
It probably occurred only in nested, dynamically created components and should be fixed now. Please reopen with more information or reproduction if it still occurs, thanks.

**Comment by ashuraits** [comment]
It happens when trying to save nested objects as localstorage decorator.
I was trying to save filters per page for my application.
My object was looking like:

```
{
   '/users' : { status : ['active','blocked'] },
   '/customers' : { name : 'John' },
    ....
} 
```
My default value was always overwriting saved value in storage.
I solved it by saving each filter object in separate key in storage (page url as a key), what is not so pretty.

**Comment by DanielKucal** [comment]
Hi @AlexShuraits, I've just tested your example. I guess you incorrectly diagnosed the problem - the data was not being overwritten - it just wasn't being saved. It's not possible to watch for nested object changes without very demanding to CPU operations, at least for today. That's why this library with enabled `mutateObjects` config option adds `.save()` method to decorated objects. You need to use this function or assign this object to itself to trigger saving...
