### ISSUE TITLE
App freezes when array in localstorage contains objects

### ISSUE THREAD

**Issue by adamk33n3r** [zoomsphere/ngx-store#7]
I'm using `@LocalStorage` with all default configuration options and when I add an object to the array the app completely freezes and uses up a ton of CPU.

**Comment by DanielKucal** [comment]
Hi @adamk33n3r, can you show the object's structure?

**Comment by adamk33n3r** [comment]
It works with anything, even `{}`. And actually I found out, this only happens when I have an `*ngFor` iterating over that array. If I take out the `*ngFor` then it doesn't freeze.

**Comment by DanielKucal** [comment]
I think the problem is somewhere else, since we use decorated array just like you described in main application:
![image](https://user-images.githubusercontent.com/8938562/27956230-1a24819e-6319-11e7-98f3-5e238a6573df.png)
![image](https://user-images.githubusercontent.com/8938562/27956249-2f01e6b0-6319-11e7-9083-d1054b4c1442.png)
And there are not any problems or app freezes... I know it could be demanding to CPU in development mode since Angular change detection has been involving in that case overridden `join()` method, but it shouldn't affect in app freezes... I've removed it from overwritten methods anyway, since it's not really needed - let me know if it solved your problem, thanks!

**Comment by DanielKucal** [comment]
Closing due to lack of response and others experiencing it.
