### ISSUE TITLE
Does not use config prefix on get?

### ISSUE THREAD

**Issue by ghost** [zoomsphere/ngx-store#79]
From what I can observe, it looks like the implementation for WebStorageService does not make use of the config.prefix when doing a `get()` for a key.  Is this by design?

I've set a prefix in the active config:
```
            LocalStorageService.config.prefix = 'kcui';

```

I can confirm it has been set by logging in the console:
```
clearType: "prefix"
cookiesCheckInterval: 0
cookiesScope: ""
debugMode: false
mutateObjects: true
prefix: "kcui"
previousPrefix: ""
```

And when I check the debugger for application local storage, I see values whose keys are prefixed with the prefix:
```
kcui.lastActivity
kcui.userId
```

However, when I use the service to get the keys, it returns null for the base key name:
```
this.localStorageService.get('userId') -> null
```

If I use the prefix in the `get()`, then the proper value is returned:
```
this.localStorageService.get('kcui.userId') -> 26439
```

This *does not* seem like expected behavior.  If I set a value using the base key, and the service then saves this in localstorage using the prefix, then I'd also expect that if I get a value using a base key the service should return the value by including the prefix with the key.

**Comment by ghost** [comment]
I also tried setting the config prefix using the webpack config:
```
        new webpack.DefinePlugin({
            NGXSTORE_CONFIG: JSON.stringify({
              prefix: 'kcui', // etc
            })
          }),
```

...and had the same behavior.

**Comment by renyuns** [comment]
什么时候支持 angular8 的版本呀? When will Angular 8 be supported?

**Comment by DanielKucal** [comment]
@donp-kitcheck ,`WebStorageService.get()` fires method `WebstorageUtility.get()` and this is where the prefix is added to the key. The config has to be set synchronously before the library gets loaded, so that's why your first approach didn't work. The second one would be working, but your prefix "kcui" is connected with key "userId" to "kcuiuserId" as ngx-store doesn't set any separator internally. So it explains why you were still getting `null` values. Change the prefix in webpack config to use prefix `"kcui."` and I hope it'll be fine.

@renyuns, as far as I know, It works with Angular 8.
